### ISSUE TITLE
compilingerror on armv7 gentoo

### ISSUE THREAD

**Issue by fleixi** [pkerling/xbmc#33]
Im trying to compile your project on an armv7 and get this error:

error: no matching function for call to ‘std::pair<const unsigned int, std::shared_ptr<KODI::WINDOWING::WAYLAND::COutput> >::pair(unsigned int&, KODI::WINDOWING::WAYLAND::COutput*)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^

and some more.

[Errorlog](https://pastebin.com/d96SbPuC)

System: Gentoo with gcc 5.4
Config: Enabled Wayland with GLES

**Comment by fritsch** [comment]
You need the latest version of: https://github.com/pkerling/waylandpp which was updated some days ago.

**Comment by yol** [comment]
Problem seems to be gcc5 - just tried to compile with 5.4.0 and hit the same problem. Will have to investigate what the exact problem is though.
@fleixi is there any chance you could use a newer compiler? gcc6 should be fine.

**Comment by yol** [comment]
@fleixi fix was easy thankfully - should compile now!

**Comment by gonciarz** [comment]
Regarding gcc6, it seems that it's widely available in Debian like distributions:
https://packages.debian.org/search?keywords=gcc-6
It's even in stable version. I'm wondering why Kodi project didn't switch to gcc6+.

**Comment by yol** [comment]
@gonciarz You can compile Kodi with whatever compiler you want as long as it supports C++11 (and is reasonably well-behaved). The Kodi project does not force you to use a specific compiler/version. I'm building with gcc7 and clang4 just fine here.

**Comment by hudokkow** [comment]
We haven't changed to gcc6+ or whatever because we have to cater for a lot of platforms, including android that still uses 4.9. Transitioning to clang would be nice.

**Comment by fleixi** [comment]
thanks it is working now to compile with 5.4

But i have switched to gcc6 after anyway since there is an other error in gcc5.4 but this is an issue for the many repo.
